import { Router, Request, Response } from 'express';
import { getSeedData } from '../seed/index';

const router = Router();

// GET /api/reports/:caseId
router.get('/:caseId', (req: Request, res: Response) => {
  const { cases, bids, vendors } = getSeedData();
  const c = cases.find(x => x.id === req.params.caseId);
  if (!c) return res.status(404).json({ error: 'Case not found' });

  const caseBids = bids.filter(b => b.tenderId === c.tenderId);
  const vendor = c.awardedTo ? vendors.find(v => v.id === c.awardedTo) : null;

  const report = {
    reportId: `RPT-${c.id}-${Date.now()}`,
    generatedAt: new Date().toISOString(),
    generatedBy: 'TenderLens',
    version: '1.0',

    summary: {
      caseId: c.id,
      tenderId: c.tenderId,
      title: c.title,
      department: c.department,
      category: c.category,
      location: c.location,
      referenceNo: c.referenceNo,
      riskScore: c.riskScore,
      riskLevel: c.riskLevel,
      caseStatus: c.caseStatus,
      assignee: c.assignee,
    },

    tenderDetails: {
      description: c.description,
      estimatedValue: c.estimatedValue,
      awardedValue: c.awardedValue,
      publishedAt: c.publishedAt,
      closingDate: c.closingDate,
      awardedAt: c.awardedAt,
      savingPercent: c.estimatedValue && c.awardedValue
        ? Math.round(((c.estimatedValue - c.awardedValue) / c.estimatedValue) * 100)
        : 0,
    },

    vendorProfile: vendor ? {
      id: vendor.id,
      name: vendor.name,
      registrationNumber: vendor.registrationNumber,
      address: vendor.address,
      city: vendor.city,
      state: vendor.state,
      directors: vendor.directors,
      establishedYear: vendor.establishedYear,
      totalContracts: vendor.totalContracts,
      totalContractsValue: vendor.totalContractsValue,
      winRate: vendor.winRate,
      riskScore: vendor.riskScore,
    } : null,

    signalBreakdown: c.signals.map(s => ({
      rule: s.rule,
      label: s.label,
      description: s.description,
      triggered: s.triggered,
      score: s.score,
      maxScore: s.maxScore,
      weight: s.weight,
      evidence: s.evidence,
    })),

    bidComparison: caseBids.map(b => ({
      vendorId: b.vendorId,
      vendorName: b.vendorName,
      bidAmount: b.bidAmount,
      technicalScore: b.technicalScore,
      financialScore: b.financialScore,
      isWinner: b.isWinner,
      disqualified: b.disqualified,
      notes: b.notes,
    })),

    timeline: [
      { date: c.publishedAt, event: 'Tender Published', description: 'Tender notice issued on government portal.' },
      { date: c.closingDate, event: 'Bid Submission Closed', description: `${caseBids.length} bid(s) received.` },
      ...(c.awardedAt ? [{ date: c.awardedAt, event: 'Contract Awarded', description: `Contract awarded to ${c.awardedToName}.` }] : []),
      ...c.auditTrail.map(a => ({ date: a.timestamp, event: a.action, description: a.detail })),
    ],

    reviewerNotes: c.notes,
    auditTrail: c.auditTrail,

    recommendations: c.riskLevel === 'critical' ? [
      'Refer to higher authority for independent review',
      'Request technical evaluation committee report',
      'Verify vendor financial capability for contract value',
      'Cross-check registered address with other active vendors',
    ] : c.riskLevel === 'high' ? [
      'Schedule desk review within 5 working days',
      'Request bid evaluation justification from department',
      'Verify vendor registration documents',
    ] : [
      'Monitor contract execution milestones',
      'Schedule periodic compliance review',
    ],

    disclaimer: 'This report is generated by the TenderLens system based on automated pattern analysis. All findings represent investigation signals and statistical patterns that warrant further review, not determinations of wrongdoing. All parties should be accorded full due process.',
  };

  res.json(report);
});

export default router;
